name: blood_bd
version: 1.1.0+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter

  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  google_mobile_ads: ^5.0.0
  change_app_package_name: ^1.1.0
  quiver: ^3.2.1
  timer_count_down: ^2.2.2
  webview_flutter: ^4.7.0


dev_dependencies: 

  flutter_test: 
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/