name: blood_bd
version: 1.1.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter

  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  change_app_package_name: ^1.4.0
  quiver: ^3.2.2
  timer_count_down: ^2.2.2
  share_plus: ^9.0.0
  webview_flutter: ^4.10.0

dev_dependencies: 

  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/