name: blood_donate_flutter_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

  provider: ^6.1.1
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.6
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

  assets:
    - assets/